export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DashboardPage } from './DashboardPage'
export { default as DocumentsPage } from './DocumentsPage'
export { default as JobDetailsPage } from './JobDetailsPage'
export { default as ControlsPage } from './ControlsPage'
export { default as AnalysisPage } from './AnalysisPage'
